# it means if you want to execute the build you have to have super user permissions
sudo: require

# installing a copy of docker CLI container created by Travis
services:
  - docker

# Series of setup that needs to occur before start of testing / deploying project
# we want to build our docker image before test run
before_install:
  - docker build -t bartek26/docker-react -f Dockerfile.dev .

# becasue we can't use container id (randomly generated), so we identify container by tag for example:
# -t docker_username/docker_repo_on_git (good convention)
# but you can name it whatever you want, because this alias will be used
# only inside this travis.yml file

# here put all commands to need to be executed to run test suite
script:
    # foreach command here Travis will be watching the output, if some command
    # return status code != 0 than Travis assume that as build failed
  - docker run -e CI=true bartek26/docker-react npm run test

# deploying the application on the selected platform
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-318411205200"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
